### ISSUE TITLE
feat: unplugin-imagemin

### ISSUE THREAD

**Issue by ErKeLost** [unplugin/.github#1]
### Clear and concise description of the problem

I wrote a vite plug-in for compressing images with unplugin. [unplugin-imagemin](https://github.com/ErKeLost/unplugin-imagemin)
If I had the opportunity, I would be honored to join unplugin.

### Suggested solution

none

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
LGTM, WDYT @sxzz?

**Comment by sxzz** [comment]
I agree too. I invited you to the org.

**Comment by sxzz** [comment]
Once you accept the invitation, you can transfer your repo to unplugin org. https://github.com/ErKeLost/unplugin-imagemin/transfer

**Comment by ErKeLost** [comment]
Thank you. It's my pleasure.
