### ISSUE TITLE
feat: unplugin-turbo-console

### ISSUE THREAD

**Issue by yuyinws** [unplugin/.github#6]
### Clear and concise description of the problem

Hello there, let me introduce this plugin first:

[unplugin-turbo-console](https://github.com/yuyinws/unplugin-turbo-console) aims to improve the Developer Experience of `console.log()`.	

Its main features include：
1. Highlight the console output based on different file types.
2. Jump to the editor source code from the console output with one click.

Here is a simple demo:
![demo](https://cdn.jsdelivr.net/gh/yuyinws/static@master/2023/12/upgit_20231203_1701565919.gif)

It was a Vite Only plugin before and received not-bad community feedback( 100+ stars on GitHub and 4k monthly downloads on npm ). Recently I refactored it with unplugin,  Now it supports more frameworks. I believe that transferring this repository to `unplugin` will lead to its better development. And I would be honored if I could join this organization.

### Suggested solution

none

### Validations

- [x] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
LGTM /cc @antfu

**Comment by antfu** [comment]
Interesting, ok 👍

**Comment by sxzz** [comment]
[I invited you](https://github.com/unplugin) to this org. Once you accepted, your repo can be transferred to unplugin org.
