### ISSUE TITLE
unplugin website

### ISSUE THREAD

**Issue by yuyinws** [unplugin/.github#8]
Hi. @antfu @sxzz 

I want to make a website for `unplugin`, like [vueuse](https://vueuse.org/) and [vue-macros](https://vue-macros.dev/). 
### website content
1. **Hero page** 
2. **Guide**: How to start developing the first unplugin package.
3. **Usage**: All content related to the usage of unplugin. Such as `Hooks`、`Nested Plugins`、`Plugin Installation`. These contents mainly come from [unjs/unplugin#readme](https://github.com/unjs/unplugin#readme.md), but with more beautiful typography.
4. **Showcase**: Show the popular plugins from the community.

### About Domain name
We can use Vercel or Netlify's domain, such as `unplugin.vercel.app` `unplugin.netlify.app` .

Do you guys think this job is necessary? or any suggestions about this?

**Comment by sxzz** [comment]
Sure. I think it would be great if we had an official docs.

**Comment by antfu** [comment]
Sure, if you want to work on it :)

**Comment by yuyinws** [comment]
Thanks for reply. I will start this project recently :)
When it's nearing completion, I will transfer it to this organization.

By the way, can you provide me the original svg file of `unplugin logo`. @antfu 

![image](https://github.com/unplugin/.github/assets/38490578/efbf2063-b6f2-4762-9c63-81031902e676)

**Comment by antfu** [comment]
Sure,
![](https://github.com/unplugin/.github/assets/11247099/f44c7a32-395b-4f63-99c2-aa927a397aed)
